# Generated by Django 4.2.6 on 2024-06-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=255, unique=True)),
                ("processor", models.CharField(blank=True, max_length=255, null=True)),
                ("gpu", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "motherboard",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("ram", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
